<?php
    $titlesFE = array(
        "The Brave Knight and the Nervous Ghost",
        "The Glowing Goblin Who Lost His Gleam",
        "The Creaky Doorway That Led to Friendship",
        "The Monster Under the Bed Who Needed a Hug",
        "The Shy Witch Who Couldn't Cast a Shadow",
        "When the Vacuum Cleaner Became Scared",
        "The Secret of Moonlight Grove",
        "The Enchanted Lighthouse",
        "The Mystery of Whispering Hollow",
        "The Brave Adventures of Lucy and Ben",
        "The Halloween Hijinks at the Haunted Hotel",
        "The Secret Room",
        "The Invisible Friend",
        "The Lost Child",
        "The Creepy Doll",
        "The Whispering Room",
        "The Haunted Playground",
        "The Ghost in the Attic",
        "The Talking Painting",
        "The Candy Curse",
        "The Haunted Diary in the Library",
        "The Knocking Sound at the Window at Night",
        "The Self-Moving Toy Horse",
        "The Long White Figure Peeking from Behind the Curtain",
        "The Haunted Halloween Train",
        "The Ghostly Chef and the Missing Halloween Pie",
        "The Ghost of the Old Haunted Clock Tower",
        "The Ghostly Haunted Hotel",
        "The Mischievous Mummy's Missing Treats",
        "Thrilling Adventure in the Ghost Cave Filled with Mysterious Sounds"
    );

    $titlesUpsell = array(
        "The Haunted Treehouse",
        "The Mystery of Silver Creek",
        "The Mystery of Whispering Shadows",
        "The Secret of Starlight Valley",
        "The Mystery of Whispering Hall",
        "The Secret of Midnight Park", 
        "The Haunting of Midnight Bear", 
        "The Secret of Forbidden Hollow", 
        "The Ghosts of Whispering Woods", 
        "The Mystery of Whispering Woods", 
        "The Curse of Misty Marsh", 
        "The Secret of Spooky Hollow", 
        "The Shadow Behind the Mirror", 
        "Forester Cat", 
        "The Whispering Doll", 
        "Mystery in the Neighbor's House", 
        "Halloween Night Adventure", 
        "Magic Pumpkin Mystery", 
        "The Mystery of the Ancient Library", 
        "Scary Halloween Night in the Bedroom", 
        "Ancient Doll Behind The Crafts", 
        "Adventure in the Mysterious Cave", 
        "Magic Lamp", 
        "Ghost of the Orange Tree", 
        "Diego and the Mysterious Ice Cream Cart", 
        "Little Witch in the Old Grave", 
        "Is My Mother a Ghost?", 
        "Spider's Nest", 
        "The Inhabitant of the Southern Beach", 
        "The Scary Tale of the Wewe Gombel Ghost Haunting Children at the Swimming Pool", 
        "The Mystery of Magic Eggs in the Home Garden", 
        "The Ghost Girl from the Old Well", 
        "The Moving Flower Vase", 
        "Scary Night at Camping", 
        "The Abandoned Graveyard's Secrets", 
        "The Mysterious Jack-o'-Lantern's Glow", 
        "The Dark School", 
        "The Chilling Legend of the Ghost Train", 
        "The Nervous Nightlight and the Big, Dark Room", 
        "The Strange Music", 
        "The Creepy Carnival", 
        "The Halloween Monster Mash", 
        "The Haunted Hayride's Screams", 
        "The Ghostly Apparition in the Halloween Mirror", 
        "The Creepy Crawlies in the Basement", 
        "The Ghostly Party Crashers", 
        "The Witch's Curse", 
        "The Clown Ghost Teaching Children about Courage", 
        "The Mystery of the Talking Painting in the Art Gallery", 
        "A Spooky Dance with the Ghostly Ballerina", 
        "The Haunted Halloween Carnival", 
        "The Dancing Ghost of the Old School Hall", 
        "The Thrilling Tale of the Vengeful Bride Ghost", 
        "Misteri The Gummy Ghost Gang", 
        "The Yurei's Forgotten Promise", 
        "The Creepy Tale of the grim faced pumpkin", 
        "The Night Cries at the Old Well: A Spooky Tale for Children", 
        "The Ghost Apparition in the Abandoned Hospital", 
        "The Spooky Spaghetti Spooked by the Chef", 
        "The Gardener Ghost Who Plants Mysterious Flowers on Halloween Night",
        "Wolf in Forest"
    );
?>